# Generated by Django 4.2.1 on 2023-05-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('1', 'SENIOR_TEACHER'), ('2', 'TEACHER'), ('3', 'EMPLOYEE')], default=1, max_length=90),
        ),
    ]
