# Generated by Django 4.2.1 on 2023-06-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_user_type_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_type',
            name='type',
            field=models.CharField(choices=[('1', 'super_user'), ('2', 'teacher'), ('3', 'student')], max_length=200),
        ),
    ]
