# Generated by Django 4.2.1 on 2023-06-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_htmlformmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmlformmodel',
            name='html',
            field=models.TextField(),
        ),
    ]
