# Generated by Django 4.2.1 on 2023-06-12 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_htmlformmodel_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmlformmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
