from django.contrib import admin
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth import logout,authenticate,login
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from app.form import *
from django.contrib import messages
from app.models import *
